name: Deployment (dev)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deployment (dev)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Node 12.16.3
        with:
          node-version: 12.16.3

      - name: yarn install and push to server
        run: |
          yarn
          yarn build

      - name: copy files to server
        uses: alpakaAlex/fantastic-octo-succotash
        with:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TARGET: ${{ secrets.TARGET }}
          source: "./.dist/*"
          strip_components: 1
